import Foundation

public enum ImageFormat: String, Equatable {
    case png
    case tiff
}

/// 过滤规则的判定结果
public enum CaptureDecision: Equatable {
    /// 记为文本：原文，不做任何修改
    case text(String)
    /// 记为图片：剪贴板里的原始数据、格式和像素尺寸
    case image(Data, format: ImageFormat, width: Int, height: Int)
    /// 跳过，附原因
    case skip(SkipReason)
}

public enum SkipReason: String, Equatable {
    case ownWrite = "本 App 自己写回的内容"
    case concealed = "带机密/临时/自动生成标记"
    case passwordApp = "来自密码类 App"
    case fileCopy = "复制的是文件"
    case emptyText = "空白文本"
    case textTooLarge = "文本超过上限"
    case imageTooLarge = "图片超过上限"
    case imageUndecodable = "图片无法解码"
    case unsupported = "没有可记录的格式"
}

public struct CaptureLimits: Equatable {
    public var maxTextBytes: Int
    public var maxImageBytes: Int

    public init(maxTextBytes: Int = Config.maxTextBytes, maxImageBytes: Int = Config.maxImageBytes) {
        self.maxTextBytes = maxTextBytes
        self.maxImageBytes = maxImageBytes
    }
}

/// 采集过滤规则 3–9（规则 1–2 在 ClipboardWatcher 里）。
/// 只做判断，不写文件、不访问系统状态。
public enum CaptureFilter {
    public static func decide(
        item: PasteboardItemSnapshot,
        source: SourceApp?,
        limits: CaptureLimits = CaptureLimits()
    ) -> CaptureDecision {
        let types = item.types
        let hasImage = types.contains(PasteboardType.png) || types.contains(PasteboardType.tiff)

        // 规则 3：本 App 写回剪贴板时带的来源标记 → 跳过（选中输入时已经更新过这条的时间）
        if types.contains(PasteboardType.source),
           item.string(forType: PasteboardType.source) == Config.bundleID {
            return .skip(.ownWrite)
        }

        // 规则 4：密码管理器、临时内容、自动生成内容的通用标记 → 跳过
        let sensitiveMarkers: Set<String> = [PasteboardType.concealed, PasteboardType.transient, PasteboardType.autoGenerated]
        if !types.isDisjoint(with: sensitiveMarkers) {
            return .skip(.concealed)
        }

        // 规则 5：来源是内置密码类 App → 跳过（兜底：有的 App 不打上面的标记）
        if let bundleID = source?.bundleID, Config.passwordAppBundleIDs.contains(bundleID) {
            return .skip(.passwordApp)
        }

        // 规则 6：带文件路径
        //   飞书/微信复制聊天图片 = 图片数据 + 临时文件路径 → 按图片记
        //   Finder 复制文件 = 文件路径 + 文件名文本，没有图片数据 → 跳过，不把文件名误记成文本
        if types.contains(PasteboardType.fileURL) {
            return hasImage ? decideImage(item: item, limits: limits) : .skip(.fileCopy)
        }

        // 规则 7：有非空白文本 → 记文本。即使同时带图片也只记文本（Excel/飞书表格复制单元格会附带渲染图）
        let text = item.plainText
        if let text, text.contains(where: { !$0.isWhitespace }) {
            // 超过上限整条不记，不截断：截断后输入回去的就是错的内容
            if text.utf8.count > limits.maxTextBytes {
                return .skip(.textTooLarge)
            }
            // 保存原文，不 trim、不改换行
            return .text(text)
        }

        // 规则 8：没有有效文本，但有图片
        if hasImage {
            return decideImage(item: item, limits: limits)
        }

        // 规则 7 补充：只有空白文本（空格、换行、全角空格等）→ 跳过
        if text != nil {
            return .skip(.emptyText)
        }

        // 规则 9：其他（只有私有格式等）→ 跳过
        return .skip(.unsupported)
    }

    /// 规则 8 的检查：优先 PNG（已压缩），其次 TIFF；超过上限或解码失败都跳过
    private static func decideImage(item: PasteboardItemSnapshot, limits: CaptureLimits) -> CaptureDecision {
        let format: ImageFormat = item.types.contains(PasteboardType.png) ? .png : .tiff
        let type = format == .png ? PasteboardType.png : PasteboardType.tiff
        guard let data = item.data(forType: type), !data.isEmpty else {
            return .skip(.imageUndecodable)
        }
        if data.count > limits.maxImageBytes {
            return .skip(.imageTooLarge)
        }
        guard let size = ImageStore.pixelSize(of: data), size.width > 0, size.height > 0 else {
            return .skip(.imageUndecodable)
        }
        return .image(data, format: format, width: size.width, height: size.height)
    }
}
