import AppKit

/// 剪贴板类型名常量
public enum PasteboardType {
    /// nspasteboard.org 约定：写入者的 Bundle ID
    public static let source = "org.nspasteboard.source"
    /// nspasteboard.org 约定：机密内容（如密码管理器复制的密码），剪贴板工具不应记录
    public static let concealed = "org.nspasteboard.ConcealedType"
    /// nspasteboard.org 约定：临时内容
    public static let transient = "org.nspasteboard.TransientType"
    /// nspasteboard.org 约定：程序自动生成的内容
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    public static let plainText = "public.utf8-plain-text"
    public static let fileURL = "public.file-url"
    public static let png = "public.png"
    public static let tiff = "public.tiff"
}

/// 剪贴板第一个条目的快照：类型列表读取时就确定，数据按需读取
///（Excel 复制一次就有十几种格式，只读用得到的那一两种）
public struct PasteboardItemSnapshot {
    public let types: Set<String>
    private let stringLoader: (String) -> String?
    private let dataLoader: (String) -> Data?

    public init(types: Set<String>, string: @escaping (String) -> String?, data: @escaping (String) -> Data?) {
        self.types = types
        self.stringLoader = string
        self.dataLoader = data
    }

    /// 纯文本；没有文本格式时为 nil
    public var plainText: String? {
        stringLoader(PasteboardType.plainText)
    }

    public func string(forType type: String) -> String? {
        stringLoader(type)
    }

    public func data(forType type: String) -> Data? {
        dataLoader(type)
    }
}

/// "读剪贴板"的抽象：正式运行用系统剪贴板，单元测试用假剪贴板
public protocol PasteboardSource: AnyObject {
    /// 系统计数器：每次有人写剪贴板就 +1
    var changeCount: Int { get }
    /// 读取第一个条目；剪贴板为空时返回 nil
    func readFirstItem() -> PasteboardItemSnapshot?
}

/// 系统剪贴板
public final class SystemPasteboard: PasteboardSource {
    private let pasteboard: NSPasteboard

    public init(_ pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    public var changeCount: Int {
        pasteboard.changeCount
    }

    public func readFirstItem() -> PasteboardItemSnapshot? {
        guard let item = pasteboard.pasteboardItems?.first else { return nil }
        return PasteboardItemSnapshot(
            types: Set(item.types.map(\.rawValue)),
            string: { item.string(forType: NSPasteboard.PasteboardType($0)) },
            data: { item.data(forType: NSPasteboard.PasteboardType($0)) }
        )
    }
}
